/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 import java.awt.event.ActionEvent;
 import java.awt.event.KeyEvent;
 import javax.swing.AbstractAction;
 import javax.swing.Action;
 import javax.swing.ActionMap;
 import javax.swing.InputMap;
 import javax.swing.JComponent;
 import javax.swing.KeyStroke;
 
 /**
  *
  * @author Jacob
  */
 public class settings extends javax.swing.JFrame {
 
     /**
      * Creates new form commands
      * @param parent The parent frame to center this window on
      */
     public settings(javax.swing.JFrame parent) {
         initComponents();
         
         setupKeyBindings();
         
         // Set the frame size explicitly to match your panel
         this.setSize(270, 400); // Width, Height (add extra for window decorations)
         
         // Center the window relative to parent
         if (parent != null) {
             setLocationRelativeTo(parent);
         }
         
     }
     
     /**
      * Sets up a key listener for the Escape key to close this window.
      * Makes the main panel focusable and adds a KeyAdapter to detect Escape key presses.
      */
     private void setupKeyBindings() {
         // Get the input map and action map for the content pane
         JComponent contentPane = (JComponent) getContentPane();
         InputMap inputMap = contentPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
         ActionMap actionMap = contentPane.getActionMap();
         
         Action escAction = new AbstractAction() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 resumeActionPerformed(null); // Call your existing settings action
             }
         };
         
         // Bind the ESC key to the action
         inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escAction");
         actionMap.put("escAction", escAction);
         
     }
     
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
 
         jPanel1 = new javax.swing.JPanel();
         resume = new javax.swing.JButton();
         saveGame = new javax.swing.JButton();
         mainMenu = new javax.swing.JButton();
         exit = new javax.swing.JButton();
         jLabel1 = new javax.swing.JLabel();
 
         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         setUndecorated(true);
 
         jPanel1.setLayout(null);
 
         resume.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
         resume.setIcon(new javax.swing.ImageIcon("assets\\images\\uiElements\\exitMenu\\resume.png")); // NOI18N
         resume.setBorderPainted(false);
         resume.setContentAreaFilled(false);
         resume.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 resumeActionPerformed(evt);
             }
         });
         jPanel1.add(resume);
         resume.setBounds(120, 70, 110, 50);
 
         saveGame.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
         saveGame.setIcon(new javax.swing.ImageIcon("assets\\images\\uiElements\\exitMenu\\save.png")); // NOI18N
         saveGame.setBorderPainted(false);
         saveGame.setContentAreaFilled(false);
         saveGame.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 saveGameActionPerformed(evt);
             }
         });
         jPanel1.add(saveGame);
         saveGame.setBounds(50, 130, 170, 50);
 
         mainMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
         mainMenu.setIcon(new javax.swing.ImageIcon("assets\\images\\uiElements\\exitMenu\\main_menu.png")); // NOI18N
         mainMenu.setBorderPainted(false);
         mainMenu.setContentAreaFilled(false);
         mainMenu.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 mainMenuActionPerformed(evt);
             }
         });
         jPanel1.add(mainMenu);
         mainMenu.setBounds(50, 200, 170, 60);
 
         exit.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
         exit.setIcon(new javax.swing.ImageIcon("assets\\images\\uiElements\\exitMenu\\exit.png")); // NOI18N
         exit.setBorderPainted(false);
         exit.setContentAreaFilled(false);
         exit.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 exitActionPerformed(evt);
             }
         });
         jPanel1.add(exit);
         exit.setBounds(50, 270, 170, 60);
 
         jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
         jLabel1.setIcon(new javax.swing.ImageIcon("assets\\images\\Backgrounds\\shelf.png")); // NOI18N
         jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
         jPanel1.add(jLabel1);
         jLabel1.setBounds(0, 0, 271, 400);
 
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
         );
 
         pack();
     }// </editor-fold>//GEN-END:initComponents
 
     private void resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeActionPerformed
         // TODO add your handling code here:
         dispose();
     }//GEN-LAST:event_resumeActionPerformed
 
     private void saveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameActionPerformed
         // TODO add your handling code here:
     }//GEN-LAST:event_saveGameActionPerformed
 
     private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
         // TODO add your handling code here:
         
         // // Get reference to the main game window
         // java.awt.Window[] windows = java.awt.Window.getWindows();
         // for (java.awt.Window window : windows) {
         //     if (window instanceof mainGame) {
         //         window.dispose();  // Close the main game window
         //         break;
         //     }
         // }
         
         // this.dispose(); // Closes the settings tab
 
         // // Open the main menu
         // mainMenu main = new mainMenu();
         
         // // Set location relative to main game window
         // main.setLocation(
         // this.getX(),  // X position of main game window
         // this.getY()   // Y position of main game window
         // );
 
         // // Make it visible
         // main.setVisible(true);
     }//GEN-LAST:event_mainMenuActionPerformed
 
     private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
         // TODO add your handling code here:
         System.exit(0);
     }//GEN-LAST:event_exitActionPerformed
 
     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
         /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
          */
         try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
                 }
             }
         } catch (ClassNotFoundException ex) {
             java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
             java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>
         //</editor-fold>
     }
 
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton exit;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JButton mainMenu;
     private javax.swing.JButton resume;
     private javax.swing.JButton saveGame;
     // End of variables declaration//GEN-END:variables
 }
 